services:
  db:
    image: postgres:16-alpine
    container_name: my-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    container_name: my-api
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    command: sh -c "npm install && npx prisma migrate deploy && node src/index.js"

volumes:
  db-data:

networks:
  backend:
